default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: api_test
  password: api_test
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: api_test_development

test:
  <<: *default
  database: api_test_test

production:
  <<: *default
  database: api_test_production
  password: <%= ENV['API_TEST_DATABASE_PASSWORD'] %>
